/**
 * Configuration file defining columns that allow special symbols
 * Add or remove column names as needed
 */
const symbolAllowedColumns = [
    'code',
  'branch',
  'location_type',
  'branch_code',
  'branch_email',
  'type',
  'rmcode',
  'branch_type',
  'imageurl',
  'rmcode',
  'subchnl',
  'rta_fund_code',
  'fund_scheme_code',
  'smf_fund_code',
  'isin',
  'broker_code',
  'arn',
  'subclass',
  'fund_code',
  'scheme_code',
  'plan_code',
  'option_code',
  'load_structure',
  'location_code',
  'transaction_code',
  'rmcode',
  'broker_code',
  'arn',
  'brok_dlr_c',
  'brok_dlr_n',
  'arn',
  'add1',
  'add2',
  'add3',
  'email1',
  'email2',
  'ifsc',
  'kyd',
  'gstin',
  'amc',
  'rmcode',
  'sm_loaddetails',
  'sm_NumschCode',
  'sm_schemecode',
  'sm_plancode',
  'stg_load_brk_sk',
  'status',
  'add1',
  'add2',
  'add3',
  'email1',
  'email2',
  'rmcode',
  'rh_code',
  'ah_code',
  'rh_perc',
  'ah_perc',
  'riacode',
  'arn',
  'imageurl',
];

const isSymbolAllowed = (columnName) => {
    return symbolAllowedColumns.includes(columnName.toLowerCase());
};

module.exports = {
    symbolAllowedColumns,
    isSymbolAllowed
};